### ISSUE TITLE
support async/await out of the box

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-caching#11]
The idea is that we should not pass `useAwait` but rather return a `Promise` if there is not callback.

```js
const redis = require('ioredis')({host: '127.0.0.1'})
const abcache = require('abstract-cache')({
  driver: {
    name: 'abstract-cache-redis', // must be installed via `npm install`
    options: {client: redis}
  }
})

const fastify = require('fastify')()
fastify
  .register(require('fastify-redis'), {client: redis})
  .register(require('fastify-caching'), {cache: abcache})

fastify.get('/', (req, reply) => {
  await fastify.cache.set('hello', {hello: 'world'}, 10000
  return {hello: 'world'}
})

fastify.listen(3000, (err) => {
  if (err) throw err
})
```

**Comment by jsumners** [comment]
This is probably better file as an issue on `abstract-cache`. I wrote it with `useAwait` because if you're not going to be using callbacks it's easier to make the library aware of that. Then the library doesn't have to do unnecessary checks for a callback each time the functions are invoked.
