### ISSUE TITLE
do not create a global cache

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-caching#12]
https://github.com/fastify/fastify-caching/blob/master/plugin.js#L8 creates a cache and places it as a singleton/global shared between all instances of fastify-caching. This should be instantiated inside the plugin creation instead, so that multiple instances of this plugin could have a different cache.

Also, it avoids potential memory leaks.

**Comment by jsumners** [comment]
This is addressed in the documentation for the `cache` option -- https://github.com/fastify/fastify-caching#options

Basically, for etags to work, we need to have a cache. I'll look into instantiating differently, but if you have a PR in mind, please submit it.
