### ISSUE TITLE
Documentation for abstract cache is wrong

### ISSUE THREAD

**Issue by AnzeKop** [fastify/fastify-caching#144]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.27.0

### Plugin version

8.3

### Node.js version

20

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

sonoma

### Description

The docs for connecting abstract-cache-redis to fastify are conflicting with the actual abstract-cache-redis docs.

In the package docs it says to pass either client or ioredis as props but the fastify caching documentation uses a different template for props which results in an error.

Also this issue https://github.com/fastify/fastify-caching/issues/132 is stil not solved for even though it has been marked as closed. Still returns void and isn't wrapped in a promise. 

Some better documentation in general would also be great - still no idea how to implement a basic cache and what this plugin handles besides giving a .cache method which is almost the same as .redis ??

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by AnzeKop** [comment]
For the type issue I think this has been fixed but it hasn't been published to the package as in the repo it looks to be correct

```
    get<T = unknown>(
      key: string | { id: string; segment: string },
      callback: (error: unknown, result: CacheResult<T>) => void
    ): void;
    /**
     * If AbstractCache is using useAwait = true, then this method-header must be used.
     * @param key
     */
    get<T = unknown>(
      key: string | { id: string; segment: string },
    ): Promise<CacheResult<T>>;
```

However if its in this order it still throws a type error, switching the 2 around for some reason fixes that

**Comment by AnzeKop** [comment]
Also to expand on the last line that I mentioned, it would be great if there was an example of implementing this with middleware/hooks

**Comment by mcollina** [comment]
I've released v8.4.0

**Comment by AnzeKop** [comment]
This fixes that issue!

**Comment by AnzeKop** [comment]
The docs would still need to be fixed
