### ISSUE TITLE
Use Keyv for cache storage

### ISSUE THREAD

**Issue by adityapatadia** [fastify/fastify-caching#15]
Keyv is much better storage system with lot of drivers already available. Can we add support for that as well?

https://github.com/lukechilds/keyv

The only challenge I see is that we need to pass `cacheSegment` differently and the keys needs to be strings.

**Comment by mcollina** [comment]
I would prefer not to drop support with what we currently have, but I’d be ok in adding support for that as well.

**Comment by adityapatadia** [comment]
Of course it's not good to break support for current one. May be we can add new parameter `keyvCache`?

**Comment by mcollina** [comment]
I think we should just throw an exception if both are provided.

Il giorno mar 18 set 2018 alle ore 13:21 Aditya Patadia <
notifications@github.com> ha scritto:

**Comment by punkish** [comment]
seems like there has been no update on this issue, but no harm in asking
