### ISSUE TITLE
old etags (aka etag removal)

### ISSUE THREAD

**Issue by millette** [fastify/fastify-caching#20]
Etags are added to the cache as they are seen, but what happens if the server updates a page and its etag (after a db change, whatever). Are requests including the previous etag still returning 304? Do we have to manage that manually, thru the abstract-cache interface?

**Comment by jsumners** [comment]
Readme seems clear:

> All incoming requests to paths affected by this plugin will be inspected for the if-none-match header. If the header is present, the value will be used to lookup the tag within the cache associated with this plugin. If the tag is found, then the response will be ended with a 304 status code sent to the client.
>
> Tags will be cached according to the second parameter. If the second parameter is supplied, and it is an integer, then it will be used as the time to cache the etag for generating 304 responses. The time must be specified in milliseconds. The default lifetime, when the parameter is not specified, is 3600000.

Once an etag is added to the cache, it is referenced for the lifetime of that cached object. If you need to remove that etag, you would need to remove it from the cache.

**Comment by millette** [comment]
Would you be interested in a PR to keep the last etag for each path, invalidating older etags?

**Comment by jsumners** [comment]
Sure.

**Comment by justintime4tea** [comment]
Interested in an invalide method. Might be able to assist if work has already started for a PR regarding this. Awesome project by the way!

**Comment by millette** [comment]
I didn't start, been busy with other stuff. Still interesting though. Feel free to take a stab at it @justintime4tea

**Comment by justintime4tea** [comment]
Perhaps it is happenstance but when I first get a resource I get the ETag, subsequent calls either If-None-Match return 304 as expected. Afterwords I issue a put to my resources route (/resource/id) and then my calls using If-None-Match with previous ETag provide the newly mutated resource with a new ETag. Seems cache is automatically invalidating for me when I update resources. If anyone's interested in my setup feel free to ping me.
