### ISSUE TITLE
Private cache control

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-caching#3]
It would be useful to implement a helper function to indicate that the current request should not be stored by shared cache. 

```
cache-control: max-age=31536000, must-revalidate, private
```

```js
reply
    .lastModified(new Date())
    .private()
    .send({hello: 'world'})
```

This functionality is provided by many http frameworks which provide auth ouf of the box.

**Comment by jsumners** [comment]
This is done at plugin initialization. Path are either private, or their not. Therefore, private paths should be encapsulated in an instance of the plugin with the appropriate privacy set.

**Comment by StarpTech** [comment]
jep, I understand.
