### ISSUE TITLE
Cache object is empty

### ISSUE THREAD

**Issue by samevision** [fastify/fastify-caching#31]
Hello guys,

unfortunately I am not able to implement this plugin successfully. The cache instance remains empty when I try to add data to it.

**app.js**
```
const redis = require('ioredis')({ host: '127.0.0.1' })
const abcache = require('abstract-cache')({
  useAwait: false,
  driver: {
    name: 'abstract-cache-redis',
    options: { client: redis }
  }
})
fastify.register(require('fastify-redis'), { client: redis })
fastify.register(require('fastify-caching'), { cache: abcache })
```

**route.js**
```
module.exports = function (fastify, opts, done) {
    fastify.get('/test', test)
    done()
}
```

**controller.js**
```
exports.test = function (req, res) {
	this.cache.set("test", {hello: "world"}, 10000, () => {
		console.log(this.cache)
		res.send(this.cache.get("test"))
	})
}
```

What's the problem here? I appreciate your help.

Best

**Comment by Eomm** [comment]
> What's the problem here? 

Did you check the errors here?

```
	this.cache.set("test", {hello: "world"}, 10000, (err) => {
		console.log(error)
		res.send(this.cache.get("test"))
	})
```

**Comment by samevision** [comment]
Yes. There is no error.

If I use "res.send(this.cache.get("test"))" I get a warning: "TypeError: callback is not a function".

But if I use only "res.send(this.cache)" everything is fine. It just prints the empty object.

**Comment by samevision** [comment]
Another issue appeared.

If I set **useAwait: true** the rendering won't work properly. I use the plugin point-of-view with pug. Sending data with "res.send" works fine but the page doesn't load if I use "res.view". With "useAwait: false" it renders without problems.

Any ideas?
