### ISSUE TITLE
Evaluate for release

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-caching#5]
@fastify/fastify please review this module. Give me a 👍 if you think it is ready to be released.

**Comment by StarpTech** [comment]
You manipulate the raw `ServerResponse` [here](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L68) You could it move it to the `onSend` hook and pass the value to the `Reply` interface.

**Comment by jsumners** [comment]
I'll get the ball rolling:

https://github.com/fastify/fastify-caching/blob/master/plugin.js#L68

That line prevents supporting Node v6. The `onResponse` hook is fired _after_ headers have been sent. That means `res.headers` is undefined in Node v6. So it wouldn't be possible to transparently cache the etag _after_ the request is finished and settled. In any hook prior to `onResponse` the header can be added and removed at any point.

**Comment by StarpTech** [comment]
@jsumners I don't get it. You mean that our hook system has a totally different behavior in Node 6?

What's the problem to move it to the `onSend` hook? `onSend` is before `onResponse`

**Comment by allevo** [comment]
Only a few things

- move the non-closure function in the main scope
- extrapolate the constants
- the cache should only check the existence of an item
- how has the cache invalidation been handled? 

For the last point consider this example

- client A requests /hello without etag. Client A store the etag value
- the resource changes
- client A requests /hello with the previous etag
- the server should responses 200 with the new entity and new etag

**Comment by StarpTech** [comment]
- Move your `onResponse` code to `OnSend` hook and set the cache item in there
- Name your plugin function to e.g `fastifyCachingPlugin` if you use lots of plugins it would have the same effect as `function`.

**Comment by jsumners** [comment]
> move the non-closure function in the main scope

Which?

> extrapolate the constants

1. the docs say not to rely on the default etag generation, so that constant does not need to be configurable. 2. the etag cache lifetime is configurable via the function invocation.

> the cache should only check the existence of an item

Um, that's what it does.

> how has the cache invalidation been handled?

That's up to the cache implementation.

> client A requests /hello without etag. Client A store the etag value
> the resource changes
> client A requests /hello with the previous etag
> the server should responses 200 with the new entity and new etag

That's the point of the etag. The requested resource should be idempotent. Therefore if the client sends a request with `if-none-exists` then the server sends a 304 if the etag is cached or resends the resource. This is all shown in the tests.

**Comment by jsumners** [comment]
> I don't get it. You mean that our hook system has a totally different behavior in Node 6?

No. The core OutgoingMessage is different in Node 6.

> What's the problem to move it to the onSend hook? onSend is before onResponse

That is exactly the problem. I outlined it in the post you replied to.

**Comment by StarpTech** [comment]
>  In any hook prior to onResponse the header can be added and removed at any point.

That's fine. It's much better instead to manipulate the raw `ServerResponse` and don't support Node v6.

**Comment by jsumners** [comment]
No, it's not really fine. The point is to be certain that the content is final before storing the state about it.

I'm not worried about Node v6. Its LTS only until April and this isn't core functionality.

**Comment by StarpTech** [comment]
What? 6.x LTS is until April 2019 [link](https://github.com/nodejs/Release)

I don't understand the problem with `onSend`. You are worried about the fact that someone can manipulate the `etag` header before the response was sent? This is always possible in another `onResponse` hook but this shouldn't be your problem. The user has to use the interface correctly. The `reply.send` method can be called only once and after that it's only possible to overwrite the state when the user plays with the raw `resp` object. @allevo did you get my point?

**Comment by jsumners** [comment]
That's the end of "maintenance." Active LTS ends in April.

**Comment by allevo** [comment]
> Which?

[here](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L34), [here](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L44) and [here](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L67)

> extrapolate the constants

[here](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L40)

> Um, that's what it does.

No, `get` retrieves the item. `has` should be better but I don't know if `@jsumners/memcache` supports it

For the other point: re-reading the code, the same entity (the output) could be linked to many `etag` value because of [this](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L38).
IMHO this is an issue. The same entity should have the same etag.

Another problem occurs during the invalidation:
- client A requests `/hello`. The server responses the entity with the etag1
- client B makes a request that invalidates the previous etag1

How can the server invalidates the etag1 (and the others)?

**Comment by jsumners** [comment]
> here, here and here

I'm sorry. I do not know what you are wanting me to do with those functions.

> here (constant)

As I said, that constant is overridable by the user and it is *expected* that the user will do so.

> No, get retrieves the item. has should be better but I don't know if @jsumners/memcache supports it

The Catbox (v7) protocol does not have a "has" -- https://github.com/hapijs/catbox/tree/v7.1.5

> For the other point: re-reading the code, the same entity (the output) could be linked to many etag value because of this.
IMHO this is an issue. The same entity should have the same etag.

The docs are clear: create your own etag and pass it in. The `uid-safe` call is just for convenience and **should not** be relied upon due to its synchronicity. Regardless, the identifiers generated by `uid-safe` are cryptographically secure. I don't see an issue.

> client B makes a request that invalidates the previous etag1

How? Does client B have access to the information sent to client A? That would be bad times for all involved.

**Comment by mcollina** [comment]
@jsumners I'm a bit lost on why you can't use `onSend`, can you please provide a link or something similar? I would avoid adding properties to `ServerResponse`.

**Comment by jsumners** [comment]
Looks like I'm out voted at least 2 to 1. I have modified it to use `onSend` instead of `onResponse`.

I do think the `onResponse` method is more complete in terms of knowing that the tag should be cached, but /shrug

**Comment by delvedor** [comment]
@jsumners you can also do something like the following:
```js
if (semver.gt(process.versions.node, '8.0.0')) {
  fastify.addHook('onResponse', ...)
} else {
  fastify.addHook('onSend', ...)
}
```

**Comment by jsumners** [comment]
@delvedor let's just keep it simple. Version checks are desperate times.

**Comment by StarpTech** [comment]
@delvedor why we do need `onResponse` at all?

**Comment by delvedor** [comment]
Was not specific to this case. What I wanted to say is that our hook system is pretty elastic, if you have a problem caused by Node versions you can easily solve it.

**Comment by jsumners** [comment]
@allevo I think I have addressed your concern with the function scopes.

**Comment by allevo** [comment]
@jsumners yeah!

I'm not convinced about [this](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L21). It could be potentially wrong.
It's up to the developer to generate the etag.

Another question: why the cache instance is exposed? Can we expose only "setETag" and "deleteETag"? If we internally always set the cache to `true` there's no reason to do [this second check](https://github.com/fastify/fastify-caching/blob/master/plugin.js#L32)

**Comment by jsumners** [comment]
Yes, it is up to the developer to generate the etag. Again, that is just for a convenient fallback.

The cache is there for the developer to use. It is a replica of how Hapi works. Hapi has an internal cache that is always available for the developer to store things. See the following test:

https://github.com/fastify/fastify-caching/blob/7719efb5920cb512fb9f66b5fee7a829c962355e/test/cache.test.js#L20-L55

**Comment by allevo** [comment]
Ok, this is a general purpose cache plugin that implements `etag` too.

LGTM

**Comment by jsumners** [comment]
Exactly. It's a one-stop-shop for caching :)

**Comment by jsumners** [comment]
Okay. I'm going to release this and we'll find out what the community thinks.
