### ISSUE TITLE
Abstract-cache with useAwait:true, and an etag on reply, causes responses to hang

### ISSUE THREAD

**Issue by bentaber** [fastify/fastify-caching#75]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

6.1.0

### Node.js version

14.147.5

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.4

### Description

Using fastify-cache with abstract-cache({ useAwait: true }) and setting an etag on reply will cause the response to hang if/when the browser sends back an etag in the `if-none-match` header.

This manfests as initial responses in browser returning as expected (because if-none-match is not sent), but any subsequent request will hang.

Same issue also with `etagOnSend`.

### Steps to Reproduce

In plugin.js... you can see that the callback passed to `this.cache.get` will never be called, if `useAwait` is true on abstract-cache.

```
function etagHandleRequest (req, res, next) {
  if (!req.headers['if-none-match']) return next()
  const etag = req.headers['if-none-match']
  this.cache.get({ id: etag, segment: this.cacheSegment }, (err, cached) => {
    if (err) return next(err)
    if (cached && cached.item) {
      return res.status(304).send()
    }
    next()
  })
}
```

### Expected Behavior

If `useAwait` is true, the `etagHandleRequest` response callback is executed after the `abstract-cache.get` promise resolves or rejects.

This could potentially also be resolved by allowing callbacks to optionally be passed and executed on promise resolution here: https://github.com/jsumners/abstract-cache/blob/master/lib/wrapCB.js...

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
Closing as this should be fixed in `abstract-cache`. Update dependencies.
