### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by simoneromano96** [fastify/fastify-caching#90]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add typescript definitions for use in typescript projects

### Motivation

I'm currently using fastify-caching in a typescript project, however there are no type definitions so typescript goes in error.
Note that the `abstract-cache` library suffers from the same issue.

### Example

```ts
import fastifyCaching from "fastify-caching"
```

```
Could not find a declaration file for module 'fastify-caching'. '/[**REDACTED**]/node_modules/fastify-caching/plugin.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/fastify-caching` if it exists or add a new declaration (.d.ts) file containing `declare module 'fastify-caching';`ts(7016)
 ```

**Comment by darkgl0w** [comment]
Hello !
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Aslam-13** [comment]
Hi, 
I have look into the issue but did not understand how to add that declaration can you pls help me. Pls assign to me as well.

**Comment by mcollina** [comment]
You can take a look at fastify-static or fastify-jwt for examples.
